modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "MIT"

[[mods]]
modId = "betterbiomes"
version = "${version}"
displayName = "${mod_name}"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "notebook.mixins.json"

[[mixins]]
config = "notebook.neoforge.mixins.json"

[[dependencies.betterbiomes]]
modId = "neoforge"
type="required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterbiomes]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

#[features.betterbiomes]
#openGLVersion="[3.2,)"
