modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/BookkeepersMC/Notebook/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL="https://curseforge.com/minecraft/mc-mods/notebook-api"
logoFile="${mod_id}.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "notebook.mixins.json"

[[mixins]]
config = "notebook.neoforge.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"