name: Build
on: [push, pull_request, merge_group]
jobs:
  build:
    strategy:
      matrix:
        java: [21-ubuntu]
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
     # - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew build --stacktrace

  check_resources:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      - run: ./gradlew generateResources --stacktrace --warning-mode=fail
      - run: ./.github/check.sh
